basePath: /
definitions:
  model.ShortenRequest:
    properties:
      url:
        type: string
    type: object
  model.ShortenResponse:
    properties:
      original_url:
        type: string
      short_url:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Simple URL shortener service
  title: URL Shortener API
  version: "1.0"
paths:
  /{code}:
    get:
      description: Redirects to the original URL by short code
      parameters:
      - description: Short code
        in: path
        name: code
        required: true
        type: string
      responses:
        "301":
          description: Moved Permanently
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Redirect to original URL
      tags:
      - urls
  /api/shorten:
    post:
      consumes:
      - application/json
      description: Creates a short URL from a long one
      parameters:
      - description: Original URL
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ShortenRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.ShortenResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Shorten URL
      tags:
      - urls
swagger: "2.0"
